Redesign edit profile page
pod4lib/aggregator pull request #526
Opened 2022-03-31 19:52 UTC by marlo-longley

Fixes #447

2022-03-31 21:07 UTC, ggeisler commented
@marlo-longley Sure, I think the biggest priority was to separate the first three fields from the change password related fields, because that part is just confusing no matter what you are trying to do. So this fixes that.

I'd still like to see a tabbed UI and better spacing (e.g., there appears to be more vertical spacing below the "Change password" heading than the "Cancel account" heading) but I agree that's lower-priority given all of the other things we're trying to update in the application now.

2022-04-01 14:07 UTC, marlo-longley commented
Thanks @ggeisler - I just fixed the vertical spacing issue for the Cancel button that you caught. Thanks!

2022-04-01 21:07 UTC, corylown requested changes
A couple of inline suggestions. Gary's mockups use different language for the new password and password confirmation fields and I'm wondering if we want to make that change in the PR:
<img width="704" alt="Screen Shot 2022-04-01 at 5 04 58 PM" src="https://user-images.githubusercontent.com/458247/161341365-8475683c-d7f8-404b-9f97-4c2f77d6d0d3.png">

2022-04-01 21:07 UTC, corylown commented on spec/features/edit_profile_spec.rb
> +      expect(page).to have_current_path('/')
Maybe this?

```suggestion
      expect(page).to have_content 'Your account has been updated successfully.'
```

2022-04-01 21:07 UTC, corylown commented on spec/features/edit_profile_spec.rb
> +      expect(page).to have_content "Current password can't be blank"
Single quotes for consistency:

```suggestion
      expect(page).to have_content 'Current password can't be blank'
```

2022-04-01 21:46 UTC, marlo-longley commented
@corylown thanks! The labels for password fields were addressed in a PR by Nick yesterday, so that's why there was a merge conflict. I rebased; should be resolved. I also changed the test as you suggested.

2022-04-01 22:03 UTC, corylown requested changes
@marlo-longley sorry! one more thing I just noticed:

This file `spec/routing/registrations_routing.spec.rb` should be named `spec/routing/registrations_routing_spec.rb`

2022-04-04 16:50 UTC, corylown approved these changes

2022-04-04 16:51 UTC, merged